<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Entry Age Procedure 1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d3ed8ef8-a253-409b-9a0f-c09065b47043</testSuiteGuid>
   <testCaseLink>
      <guid>fadb7347-93fa-48f0-b31a-58bf346257fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/AlterationScoringNBMajor/Entry Age Procedure 1/Entry Age Procedure 1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfe11f2b-c0f3-4974-b8fa-70d04d2dad60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9449514-408c-43f2-bb8d-2675d57811b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e23fc2e2-8c92-471a-abb1-fe2182fb9fc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>181edb1a-4564-4e6f-a022-a7888806a5b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82e840a8-14aa-454f-b0e3-e349ea4d19e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa944051-dc54-45a9-b41d-c7954b05ef26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b8ad020-1dc6-4568-b3d0-08154e7df099</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AlterationScoringNBMajor/Entry Age Procedure 1/Negative-Entry Age Procedure 1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2206de9c-4913-49cb-90ab-2ab2d3e84824</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>137edc27-f9e8-48e6-836e-0431d561a349</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>434e2214-011a-46dc-b369-7bf9a25a383a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa73e536-92d9-4f09-99c9-3420cf9ad1c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8886d792-a75e-4a8b-b9fc-bdd28a974977</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee6e8a8-4f55-4602-8615-3cbd783f037b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
